#!/usr/bin/perl

use strict;

# - latexpand   D. Musliner University of Michigan
# Short program to expand out LaTeX \input and \include commands.
# Essentially a tiny part of 'go' hacked out.
# Removes comments as a side effect, does not deal with escaped %s.
#
# 15 Sept 1999  M. Lovell       Hewlett-Packard, Co
# Improved comment removal code.  Now handles escaped %'s.
#
# Source: http://tex.stackexchange.com/questions/25713/how-do-i-combine-several-tex-files-into-one
#
# 11/12/12: improvements... (Fabrice)

use Getopt::Std;
use File::Copy;

my $TEXINPUTS = $ENV{'TEXINPUTS'};
if (!$TEXINPUTS) { $TEXINPUTS = '.'; }

my %Opts;
getopt('', \%Opts);

if(@ARGV != 2){
  die "Usage:\n  perl [-e] latexexpand.pl in.tex out.tex\n    -e embed in.bbl in out.tex instead of copying it to out.bbl";
}

my ($infname, $outfname) = @ARGV;

open(OUT, ">${outfname}") or die "ERROR: cannot open [$outfname]";

my $inbibfname = $infname;
$inbibfname =~ s/\.tex$/\.bbl/;
my $outbibfname = $outfname;
$outbibfname =~ s/\.tex$/\.bbl/;

print OUT "%% This file has been automatically generated by latexexpand.pl\n";
print OUT "%% DO NOT MANUALLY MODIFY THIS FILE\n";

if($Opts{e}){
  if(open(FILE, $inbibfname)){
    print OUT "\\begin{filecontents*}{${outbibfname}}\n";
    while(<FILE>){
      print OUT
    }
    print OUT "\\end{filecontents*}\n";
    close(FILE);
  }else{
    warn "WARNING: could not open [$outbibfname]\n";
  }
}else{
  copy($inbibfname,$outbibfname);
}

&scan_for_includes($infname);

#************************************************************
# looks recursively for included & inputted files, expands.

sub scan_for_includes{
  local(*FILE); 
  if(!open(FILE,$_[0])){ 
    warn "WARNING: could not open input file [$_[0]]\n"; 
    return; 
  }
  while(<FILE>){
    # comment removal
    s/^%.*$/%/;
    s/([^\\])%.*$/$1%/;

    if(/\\(?:include|input)[{\s]+([^\001}]*)[\s}]/){
        my $full_filename = $1;
        if($1 =~ m/\./){ 
          $full_filename = &find_file($full_filename); 
        }else{ 
          $full_filename = &find_file("$full_filename.tex"); 
        }
        &scan_for_includes($full_filename);
    }else{ 
      print OUT; 
    }
  }
  close(FILE);
}

#************************************************************
# given filename and path, return full name of file, or die if none found.

sub find_file{
  my $dir;
  foreach $dir (split(':', $TEXINPUTS)){ 
    if (-e "$dir/$_[0]"){ 
      return("$dir/$_[0]"); 
    } 
  }
  die "ERROR: Could not find file [$_[0]] in path [$_[1]]\n";
}
